### ISSUE TITLE
Mondschein: Player speed too high in cutscenes

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/Player#1261]
**Name of the game**: Mondschein ([download](http://www.rpg2000.4players.de/index.php?inhalt=download&id=234))

#### Describe the issue in detail and how to reproduce it:

Start the game and watch the intro for one minute, then you run away from your mother... 🏃

![test](https://user-images.githubusercontent.com/4691314/30253019-f3358438-967c-11e7-864c-9f25b6d351f7.gif)
(left is RPG_RT, right is Player)

The same seems to happen later in the game, when you again run away from 3 girls (not verified myself, was reported on google play)

Relevant Map: `5 (erzählung-weg)`. Both the Player and the `[mother]` event have a custom move route containing just "Move Left" commands at frequency 8, nothing special.

**Comment by Ghabry** [comment]
I guess this is caused by a page switch. In that case the moveroute speed is overwritten due to a bug.

**Comment by carstene1ns** [comment]
Another turbo bug happens when stepping on the slide in Grimps - Level 4:
https://youtu.be/-R_NyRr6Sz0?t=9m32s

In Player, the slide does not work correctly and you stop midway while the actor speed is too high afterwards.

Nothing too fancy here about the "ICE" Events:
![screenshot](https://p.f4ke.de/XjhgFvvzpj.png)

**Comment by Ghabry** [comment]
The Mondschein bug is caused by the last move command executed in the event on the map "Schwarzer Bildschirm" which is "Increase Move Speed, Increase Move Speed" followed by a teleport. The move command is not executed on RPG_RT and the move speed stays low. When you put a "Wait for All Movement" before the teleport the fast movement issue is also in RPG_RT.

**Comment by Ghabry** [comment]
via Event Tracer plugin I observed that no Move commands are executed during the first frame on the new map.
Even when not a single event runs on the new map the movement will be one frame late.

**Comment by Ghabry** [comment]
Fixed the problems in Grimps @carstene1ns but that was a completely different bug ^^'

**Comment by fmatthew5876** [comment]
This can be distilled down to a very simple test case

Create 2 maps. 

Map 1 has autostart event
```
SetMoveRoute: Player, Increase Speed, Increase Speed
Teleport to Map 2
```

Map 2 has autostart event
```
SetMoveRoute: Player, Right, Right, Right, Right, Right
```

In RPG_RT, the player walks at normal speed. In Player, the player walks fast.

**Comment by fmatthew5876** [comment]
There are 2 things causing this issue.

1. The second item in #1606 (Fixed in #1601)
2. In Player, when a teleport is started events are allowed to process 1 extra frame when the teleports begin. This extra frame allows the move speed up commands to apply.

**Comment by fmatthew5876** [comment]
Unfortunately this is still broken in #1694 

My test case, the frame timing in RPG_RT must be this:
* Preupdate - nothing happens
* Player updates
* autostart sets move route on player
* autostart initiates teleport
* Preupdate runs on map2 - player not updated
* *Normal update - something blocks the player update route!* :question:
* Autostart runs - sets new move route for player to walk

So something is blocking the player update routine from running on the first frame of map2. Which prevents the move speed up commands from executing.
